# Generated by Django 6.0.2 on 2026-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_avatar_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="avatars/"
            ),
        ),
    ]
