# Generated by Django 6.0.2 on 2026-02-18 18:41

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение (максимум 5 МБ, поддерживаемые форматы: JPG, PNG, WEBP)",
                null=True,
                upload_to="images/%Y/%m/%d/",
                validators=[blog.models.validate_image_file],
            ),
        ),
    ]
