# Generated by Django 6.0.3 on 2026-04-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_author_comment_user_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='aythor',
        ),
    ]
