# Generated by Django 6.0.3 on 2026-04-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_user_comment_aythor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aythor',
            new_name='author',
        ),
    ]
