# Generated by Django 6.0.2 on 2026-03-14 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_comment_user"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-publish", "-created"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_bb7600_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-publish", "-created", "status"],
                name="blog_post_publish_27739a_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="post",
            table="blog_post",
        ),
    ]
