# Generated by Django 6.0.3 on 2026-03-16 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="fixed",
            field=models.BooleanField(default=False, verbose_name="Исправлено"),
        ),
        migrations.AddField(
            model_name="post",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто обновил",
            ),
        ),
    ]
