# Generated by Django 6.0.3 on 2026-03-24 10:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_comment_parent_alter_comment_post_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(verbose_name="Полный текст записи"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=ckeditor.fields.RichTextField(
                max_length=500, verbose_name="Краткое описание"
            ),
        ),
    ]
