# Generated by Django 6.0.3 on 2026-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.IntegerField(
                choices=[(1, "Нравится"), (-1, "Не нравится")], verbose_name="Значение"
            ),
        ),
    ]
