# Generated by Django 6.0.3 on 2026-04-03 09:13

import blog.models
import django.db.models.deletion
import django_ckeditor_5.fields
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полный текст записи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение (максимум 5 МБ, поддерживаемые форматы: JPG, PNG)', null=True, upload_to=blog.models.post_image_upload_to, validators=[blog.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Поддерживается форматирование, но избегайте слишком длинных заголовков.', max_length=500, verbose_name='Краткое описание'),
        ),
    ]
